### Add a Ticket
POST http://127.0.0.1:3000/Tickets
Content-Type: application/json

{
    "Subject":"TEST"
}

### Get a Listing of all tickets
GET http://127.0.0.1:3000/Tickets


### Authenticate
POST http://127.0.0.1:3000/auth
Content-Type: application/json

{
    "username":"test",
    "password":"testpass"
}